### ISSUE TITLE
Use OpenTSDB + AsyncBigtable released binaries instead of building OpenTSDB + Bigtable support from source

### ISSUE THREAD

**Issue by mbrukman** [GoogleCloudPlatform/opentsdb-bigtable#1]
The current version of the [`Dockerfile`](https://github.com/GoogleCloudPlatform/opentsdb-bigtable/blob/c7da472040780b53a57fb679b3a08beb2a853526/build/Dockerfile#L27-L29) says:

> ```docker
> RUN git clone https://github.com/OpenTSDB/opentsdb.git && \
>     cd opentsdb && \
>     sh build-bigtable.sh install
> ```

which is downloading and building everything from source. Why not use the releases of [OpenTSDB](https://github.com/opentsdb/opentsdb/releases) + [AsyncBigtable](https://github.com/opentsdb/asyncbigtable/releases) instead?

/cc: @sduskis, @igorbernstein2, @ghaisa (FYI)

**Comment by nvtkaszpir** [comment]
It's because OpenTSDB official binaries provide code for Hbase only, and not BigTable.
OpenTSDB docs explicitly explain how to build it on your own, and that's wy this repo does it.
