### ISSUE TITLE
OpenTsDB API Issue

### ISSUE THREAD

**Issue by Rokshan2016** [GoogleCloudPlatform/opentsdb-bigtable#16]
Hi @varundhussa

I used this opentsdb-bigtable wrapper and able to install opentsdb in GCP environment. But I am getting the following issues while retrieving the  data back from bigtable through opentsdb API

1. For a new environment, I need to insert at-least 3000 records before I could use this query API 
api/query?start=2h-ago&m=sum:ppc.event.alert&show_tsuids=true

2. Then, for each metric I need to insert at least 10 record to get the result through API 

I tried to use this configuration but did not change anything. 
tsd.storage.flush_interval=1000

We are trying to use this for our production environment, any suggestion will be really helpful. Thanks!

**Comment by varundhussa** [comment]
Try adding google.bigtable.bulk.autoflush.ms = 1000

**Comment by Rokshan2016** [comment]
Thanks, will try.

**Comment by Rokshan2016** [comment]
@varundhussa Its fixed :). Where is this configuration documented ?

Thanks!

**Comment by varundhussa** [comment]
The Bigtable client configurations can be found here: https://cloud.google.com/bigtable/docs/hbase-client/javadoc/constant-values

**Comment by Rokshan2016** [comment]
Great! thanks for the help.
