### ISSUE TITLE
Grafana pod fails.

### ISSUE THREAD

**Issue by seanlubbers1** [GoogleCloudPlatform/opentsdb-bigtable#8]
One of our Qwiklabs "Using OpenTSDB to Monitor Time-Series Data on Cloud Platform" (https://google.qwiklabs.com/labs/775/), which is built from a similarly named tutorial (https://cloud.google.com/solutions/opentsdb-cloud-platform) hasn't been working as of late.

In the "Examining time-series data with OpenTSDB" task, we are getting error while executing command: kubectl port-forward $grafana 8080:3000. Looking at the set of GKE pods, it says that the grafana pod "does not have minimum availability" and keeps crashing.

Any ideas on what could be causing this?
![grafana-pod](https://user-images.githubusercontent.com/39922333/67814635-c6777500-fa61-11e9-9837-f0521ed520fe.png)
![grafana-port](https://user-images.githubusercontent.com/39922333/67814637-c6777500-fa61-11e9-85d0-9cd5f4a73d4a.png)

**Comment by igorbernstein2** [comment]
Can you post some logs from the pod that contains the opentsdb big table client?

**Comment by seanlubbers1** [comment]
Here are some from the Grafana pod:
<img width="1375" alt="Screen Shot 2019-10-31 at 12 37 26 PM" src="https://user-images.githubusercontent.com/39922333/67980259-4aa13800-fbdb-11e9-8490-979db5b0099a.png">

<img width="1375" alt="Screen Shot 2019-10-31 at 12 37 26 PM" src="https://user-images.githubusercontent.com/39922333/67980284-54c33680-fbdb-11e9-8acc-2d426c8a0e72.png">

**Comment by seanlubbers1** [comment]
CCed you on buganizer ticket too

**Comment by samizuh** [comment]
version pinning missing for container
